name:                hs-playground
version:             0.1.0.0
github:              "kurtlippert/hs-playground"
license:             BSD3
author:              "Kurt Lippert"
maintainer:          "kurtlippert@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kurtlippert/hs-playground#readme>

dependencies:
- base >= 4.7 && < 5
- hoogle == 5.0.18.1

library:
  source-dirs: src

executables:
  hs-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-playground

tests:
  hs-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-playground
